watch:
	dotnet watch run

dev-css:
	NODE_ENV=development yarn parcel build css/styles.css --out-dir wwwroot/ --no-minify

build-css:
	NODE_ENV=production yarn parcel build css/styles.css --out-dir wwwroot/
